version: '3'

services:
  mysqlsrv:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "MySql!"
      MYSQL_DATABASE: "db_pizzeria"
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./db/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    container_name: adminer_mysql
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge